import type { Locale } from "@/utils/locale";

export const toolCategories = ["Mechanical", "Automotive", "General Engineering"] as const;
export type ToolCategory = (typeof toolCategories)[number];

export const toolTags = [
  "pressure",
  "torque",
  "flow",
  "thermal",
  "units",
  "validation",
  "sensitivity",
  "montecarlo",
  "engineering",
] as const;
export type ToolTag = (typeof toolTags)[number];

export const toolTypes = ["calculator", "bundle", "guide"] as const;
export type ToolType = (typeof toolTypes)[number];

export type ToolCatalogItem = {
  id: string;
  type: ToolType;
  title: string;
  description: string;
  titleEn?: string;
  descriptionEn?: string;
  href: string;
  category?: ToolCategory;
  tags?: ToolTag[];
  lastUpdated?: string;
};

export const toolCatalog: ToolCatalogItem[] = [
  {
    id: "bolt-calculator",
    type: "calculator",
    title: "Cıvata Boyut ve Tork",
    description: "Nominal çap, diş adımı ve kalite sınıfına göre gerilme alanı ve ön yük hesabını yap.",
    titleEn: "Bolt Size & Torque",
    descriptionEn: "Calculate stress area and preload from nominal diameter, pitch, and grade.",
    href: "/tools/bolt-calculator",
    category: "Mechanical",
    tags: ["torque"],
  },
  {
    id: "unit-converter",
    type: "calculator",
    title: "Birim Dönüştürücü",
    description: "Uzunluk, kuvvet, basınç ve enerji için hızlı birim dönüşümleri.",
    titleEn: "Unit Converter",
    descriptionEn: "Fast unit conversions for length, force, pressure, and energy.",
    href: "/tools/unit-converter",
    category: "General Engineering",
  },
  {
    id: "sanity-check",
    type: "calculator",
    title: "Mühendislik Kontrol Laboratuvarı",
    description: "Değişkenleri, birimleri ve formül sonucunu tek ekranda doğrula.",
    titleEn: "Engineering Sanity Check Lab",
    descriptionEn: "Validate variables, units, and formulas in one screen.",
    href: "/tools/sanity-check",
    category: "General Engineering",
    tags: ["units", "validation", "sensitivity", "montecarlo", "engineering"],
    lastUpdated: "2026-02-02",
  },
  {
    id: "basic-engineering",
    type: "calculator",
    title: "Basit Isı Akışı",
    description: "Tek katmanlı iletim için ısı akışını manuel parametrelerle hesapla.",
    titleEn: "Basic Heat Flow",
    descriptionEn: "Estimate heat flow through a single layer with manual inputs.",
    href: "/tools/basic-engineering",
    category: "General Engineering",
    tags: ["thermal"],
  },
  {
    id: "param-chart",
    type: "calculator",
    title: "Yay Kuvvet Grafiği",
    description: "Yay sabiti ve yer değiştirme ile F-x grafiği üret.",
    titleEn: "Spring Force Chart",
    descriptionEn: "Generate an F-x chart from spring constant and displacement.",
    href: "/tools/param-chart",
    category: "Mechanical",
  },
  {
    id: "simple-stress",
    type: "calculator",
    title: "Çekme Gerilmesi",
    description: "Kuvvet ve kesit alanına göre çekme gerilmesini hesapla.",
    titleEn: "Tensile Stress",
    descriptionEn: "Compute tensile stress from force and cross-section area.",
    href: "/tools/simple-stress",
    category: "Mechanical",
    tags: ["pressure"],
  },
  {
    id: "bending-stress",
    type: "calculator",
    title: "Eğilme ve Sehim",
    description: "Basit mesnetli kiriş için eğilme gerilmesi ve maksimum sehim hesabı.",
    titleEn: "Bending & Deflection",
    descriptionEn: "Bending stress and max deflection for a simply supported beam.",
    href: "/tools/bending-stress",
    category: "Mechanical",
    tags: ["pressure"],
  },
  {
    id: "bolt-database",
    type: "guide",
    title: "Cıvata Veri Merkezi",
    description: "Metrik ve imperial cıvata ölçülerine hızlı erişim sağla.",
    titleEn: "Bolt Data Center",
    descriptionEn: "Quick access to metric and imperial bolt sizes.",
    href: "/tools/bolt-database",
    category: "Mechanical",
  },
  {
    id: "compressor-cc",
    type: "calculator",
    title: "Kompresör CC",
    description: "Piston çapı, strok ve rpm ile hacimsel kapasiteyi tahmin et.",
    titleEn: "Compressor CC",
    descriptionEn: "Estimate displacement from bore, stroke, and rpm.",
    href: "/tools/compressor-cc",
    category: "Automotive",
    tags: ["flow"],
  },
  {
    id: "belt-length",
    type: "calculator",
    title: "Kasnak Kayış Uzunluğu",
    description: "İki kasnak çapı ve merkez mesafesine göre kayış uzunluğunu hesapla.",
    titleEn: "Pulley Belt Length",
    descriptionEn: "Calculate belt length from pulley diameters and center distance.",
    href: "/tools/belt-length",
    category: "Mechanical",
  },
  {
    id: "torque-power",
    type: "calculator",
    title: "Güç - Tork - Devir",
    description: "kW, hp ve rpm ilişkisine göre tork veya güç hesabını yap.",
    titleEn: "Power - Torque - RPM",
    descriptionEn: "Compute torque or power from kW, hp, and rpm.",
    href: "/tools/torque-power",
    category: "Mechanical",
    tags: ["torque"],
    lastUpdated: "2026-01-29",
  },
  {
    id: "strength-statics",
    type: "bundle",
    title: "Mukavemet ve Statik",
    description: "Eksenel, kesme ve burkulma için hızlı mukavemet hesapları.",
    titleEn: "Strength & Statics",
    descriptionEn: "Quick strength checks for axial, shear, and buckling.",
    href: "/tools/strength-statics",
    category: "Mechanical",
    tags: ["pressure"],
  },
  {
    id: "machine-elements",
    type: "bundle",
    title: "Makine Elemanları",
    description: "Rulman ömrü, kamalı mil ve dişli yükleri için hesaplar.",
    titleEn: "Machine Elements",
    descriptionEn: "Calculations for bearing life, keyed shafts, and gear loads.",
    href: "/tools/machine-elements",
    category: "Mechanical",
  },
  {
    id: "fluids-hvac",
    type: "bundle",
    title: "Akışkanlar ve HVAC",
    description: "Reynolds, basınç kaybı ve kanal hızı için hızlı hesaplar.",
    titleEn: "Fluids & HVAC",
    descriptionEn: "Quick calculations for Reynolds, pressure loss, and duct velocity.",
    href: "/tools/fluids-hvac",
    category: "General Engineering",
    tags: ["flow", "pressure"],
  },
  {
    id: "heat-energy",
    type: "bundle",
    title: "Isı Transferi ve Enerji",
    description: "LMTD, iletim ve enerji tahminleri için temel hesaplar.",
    titleEn: "Heat Transfer & Energy",
    descriptionEn: "Basics for LMTD, conduction, and energy estimates.",
    href: "/tools/heat-energy",
    category: "General Engineering",
    tags: ["thermal"],
  },
  {
    id: "materials-manufacturing",
    type: "bundle",
    title: "Malzeme ve İmalat",
    description: "Kesme parametreleri ve toleransları için hızlı karar yardımı.",
    titleEn: "Materials & Manufacturing",
    descriptionEn: "Quick decisions for cutting parameters and tolerances.",
    href: "/tools/materials-manufacturing",
    category: "General Engineering",
  },
  {
    id: "production-project",
    type: "bundle",
    title: "Üretim ve Proje",
    description: "Takt, OEE ve proje süreleri için pratik hesaplamalar.",
    titleEn: "Production & Project",
    descriptionEn: "Practical calculations for takt, OEE, and project durations.",
    href: "/tools/production-project",
    category: "General Engineering",
  },
  {
    id: "gear-design",
    type: "guide",
    title: "Dişli Tasarımı",
    description: "Dişli tasarımı için genel bakış ve temel hesaplama girişi.",
    titleEn: "Gear Design",
    descriptionEn: "Overview and entry point for gear design calculations.",
    href: "/tools/gear-design",
    category: "Mechanical",
    tags: ["torque"],
  },
  {
    id: "gear-calculators",
    type: "bundle",
    title: "Dişli Hesaplayıcılar",
    description: "Dişli oranı, modülü ve temas değerleri için hesaplayıcılar.",
    titleEn: "Gear Calculators",
    descriptionEn: "Calculators for gear ratio, module, and contact values.",
    href: "/tools/gear-design/calculators",
    category: "Mechanical",
  },
  {
    id: "gear-backlash",
    type: "calculator",
    title: "Dişli Backlash",
    description: "Backlash değişimini ve uygun ayar aralığını hesapla.",
    titleEn: "Gear Backlash",
    descriptionEn: "Estimate backlash and recommended adjustment range.",
    href: "/tools/gear-design/calculators/backlash-calculator",
    category: "Mechanical",
  },
  {
    id: "gear-contact-ratio",
    type: "calculator",
    title: "Dişli Temas Oranı",
    description: "Dişli temas oranını ve güvenli temas sınırını hesapla.",
    titleEn: "Gear Contact Ratio",
    descriptionEn: "Calculate contact ratio and safe contact limits.",
    href: "/tools/gear-design/calculators/contact-ratio-calculator",
    category: "Mechanical",
  },
  {
    id: "gear-force-torque",
    type: "calculator",
    title: "Dişli Kuvvet ve Tork",
    description: "Dişli torku ve taşıyıcı kuvvetleri hesapla.",
    titleEn: "Gear Force & Torque",
    descriptionEn: "Compute gear torque and transmitted forces.",
    href: "/tools/gear-design/calculators/force-torque-calculator",
    category: "Mechanical",
    tags: ["torque"],
  },
  {
    id: "gear-helix-axial",
    type: "calculator",
    title: "Helis Dişli Aksiyel",
    description: "Helis dişlilerde aksiyel kuvvet ve helis etkisini hesapla.",
    titleEn: "Helical Gear Axial",
    descriptionEn: "Calculate axial force and helix effect in helical gears.",
    href: "/tools/gear-design/calculators/helix-axial-calculator",
    category: "Mechanical",
  },
  {
    id: "gear-module",
    type: "calculator",
    title: "Dişli Modül",
    description: "Dişli modülünü ve temel boyutları hesapla.",
    titleEn: "Gear Module",
    descriptionEn: "Compute gear module and base dimensions.",
    href: "/tools/gear-design/calculators/module-calculator",
    category: "Mechanical",
  },
  {
    id: "gear-ratio",
    type: "calculator",
    title: "Dişli Oranı",
    description: "Dişli oranını ve çıkış hızını hesapla.",
    titleEn: "Gear Ratio",
    descriptionEn: "Calculate gear ratio and output speed.",
    href: "/tools/gear-design/calculators/ratio-calculator",
    category: "Mechanical",
  },
  {
    id: "gear-viscosity",
    type: "calculator",
    title: "Dişli Yağ Viskozitesi",
    description: "Dişli yağlama viskozitesi için hızlı seçim aracı.",
    titleEn: "Gear Oil Viscosity",
    descriptionEn: "Quick selector for gear lubrication viscosity.",
    href: "/tools/gear-design/calculators/viscosity-selector",
    category: "Mechanical",
  },
  {
    id: "gear-weight",
    type: "calculator",
    title: "Dişli Ağırlık Optimizasyonu",
    description: "Dişli ağırlığını azaltmak için basit optimizasyon aracı.",
    titleEn: "Gear Weight Optimization",
    descriptionEn: "Simple tool to reduce gear weight.",
    href: "/tools/gear-design/calculators/weight-optimization",
    category: "Mechanical",
  },
  {
    id: "gear-simulations",
    type: "bundle",
    title: "Dişli Simülasyonları",
    description: "Dişli davranışını test etmek için simülasyon sayfası.",
    titleEn: "Gear Simulations",
    descriptionEn: "Simulation pages to test gear behavior.",
    href: "/tools/gear-design/simulations",
    category: "Mechanical",
  },
  {
    id: "sealing-guide",
    type: "guide",
    title: "Sızdırmazlık Rehberi",
    description: "Conta ve sızdırmazlık elemanları için pratik referanslar.",
    titleEn: "Sealing Guide",
    descriptionEn: "Practical references for seals and sealing elements.",
    href: "/tools/sealing-guide",
    category: "General Engineering",
  },
  {
    id: "coating-guide",
    type: "guide",
    title: "Kaplama Rehberi",
    description: "Kaplama türleri ve korozyon koruması için özet bilgi.",
    titleEn: "Coating Guide",
    descriptionEn: "Summary of coating types and corrosion protection.",
    href: "/tools/coating-guide",
    category: "General Engineering",
  },
  {
    id: "material-cards",
    type: "guide",
    title: "Malzeme Kartları",
    description: "Malzeme özelliklerine hızlı ulaşım için kartlar.",
    titleEn: "Material Cards",
    descriptionEn: "Cards for quick access to material properties.",
    href: "/tools/material-cards",
    category: "General Engineering",
  },
  {
    id: "heat-treatment",
    type: "guide",
    title: "Isıl İşlem",
    description: "Isıl işlem adımları ve pratik kalite kontrol notları.",
    titleEn: "Heat Treatment",
    descriptionEn: "Heat treatment steps and quality control notes.",
    href: "/tools/heat-treatment",
    category: "General Engineering",
  },
];

export const getToolCopy = (tool: ToolCatalogItem, locale: Locale) => {
  if (locale === "en") {
    return {
      title: tool.titleEn ?? tool.title,
      description: tool.descriptionEn ?? tool.description,
    };
  }
  return { title: tool.title, description: tool.description };
};

