import type { Locale } from "@/utils/locale";

export const toolCategories = ["Mechanical", "Automotive", "General Engineering"] as const;
export type ToolCategory = (typeof toolCategories)[number];

export const toolTags = [
  "pressure",
  "torque",
  "flow",
  "thermal",
  "units",
  "validation",
  "sensitivity",
  "montecarlo",
  "engineering",
] as const;
export type ToolTag = (typeof toolTags)[number];

export const toolTypes = ["calculator", "bundle", "guide"] as const;
export type ToolType = (typeof toolTypes)[number];

export type ToolCatalogItem = {
  id: string;
  type: ToolType;
  title: string;
  description: string;
  titleEn?: string;
  descriptionEn?: string;
  href: string;
  category?: ToolCategory;
  tags?: ToolTag[];
  lastUpdated?: string;
};

export const toolCatalog: ToolCatalogItem[] = [
  {
    id: "bolt-calculator",
    type: "calculator",
    title: "Civata Boyut ve Tork",
    description: "Nominal cap, dis adimi ve kalite sinifina gore gerilme alani ve on yuk hesabini yap.",
    titleEn: "Bolt Size & Torque",
    descriptionEn: "Calculate stress area and preload from nominal diameter, pitch, and grade.",
    href: "/tools/bolt-calculator",
    category: "Mechanical",
    tags: ["torque"],
  },
  {
    id: "unit-converter",
    type: "calculator",
    title: "Birim Donusturucu",
    description: "Uzunluk, kuvvet, basinc ve enerji icin hizli birim donusumleri.",
    titleEn: "Unit Converter",
    descriptionEn: "Fast unit conversions for length, force, pressure, and energy.",
    href: "/tools/unit-converter",
    category: "General Engineering",
  },
  {
    id: "sanity-check",
    type: "calculator",
    title: "Muhendislik Kontrol Laboratuvari",
    description: "Degiskenleri, birimleri ve formul sonucunu tek ekranda dogrula.",
    titleEn: "Engineering Sanity Check Lab",
    descriptionEn: "Validate variables, units, and formulas in one screen.",
    href: "/tools/sanity-check",
    category: "General Engineering",
    tags: ["units", "validation", "sensitivity", "montecarlo", "engineering"],
    lastUpdated: "2026-02-02",
  },
  {
    id: "basic-engineering",
    type: "calculator",
    title: "Basit Isi Akisi",
    description: "Tek katmanli iletim icin isi akisini manuel parametrelerle hesapla.",
    titleEn: "Basic Heat Flow",
    descriptionEn: "Estimate heat flow through a single layer with manual inputs.",
    href: "/tools/basic-engineering",
    category: "General Engineering",
    tags: ["thermal"],
  },
  {
    id: "param-chart",
    type: "calculator",
    title: "Yay Kuvvet Grafigi",
    description: "Yay sabiti ve yer degistirme ile F-x grafigi uret.",
    titleEn: "Spring Force Chart",
    descriptionEn: "Generate an F-x chart from spring constant and displacement.",
    href: "/tools/param-chart",
    category: "Mechanical",
  },
  {
    id: "simple-stress",
    type: "calculator",
    title: "Cekme Gerilmesi",
    description: "Kuvvet ve kesit alanina gore cekme gerilmesini hesapla.",
    titleEn: "Tensile Stress",
    descriptionEn: "Compute tensile stress from force and cross-section area.",
    href: "/tools/simple-stress",
    category: "Mechanical",
    tags: ["pressure"],
  },
  {
    id: "bending-stress",
    type: "calculator",
    title: "Egilme ve Sehim",
    description: "Basit mesnetli kiris icin egilme gerilmesi ve maksimum sehim hesabi.",
    titleEn: "Bending & Deflection",
    descriptionEn: "Bending stress and max deflection for a simply supported beam.",
    href: "/tools/bending-stress",
    category: "Mechanical",
    tags: ["pressure"],
  },
  {
    id: "bolt-database",
    type: "guide",
    title: "Civata Veri Merkezi",
    description: "Metrik ve imperial civata olculerine hizli erisim sagla.",
    titleEn: "Bolt Data Center",
    descriptionEn: "Quick access to metric and imperial bolt sizes.",
    href: "/tools/bolt-database",
    category: "Mechanical",
  },
  {
    id: "compressor-cc",
    type: "calculator",
    title: "Kompresor CC",
    description: "Piston capi, strok ve rpm ile hacimsel kapasiteyi tahmin et.",
    titleEn: "Compressor CC",
    descriptionEn: "Estimate displacement from bore, stroke, and rpm.",
    href: "/tools/compressor-cc",
    category: "Automotive",
    tags: ["flow"],
  },
  {
    id: "belt-length",
    type: "calculator",
    title: "Kasnak Kayis Uzunlugu",
    description: "Iki kasnak capi ve merkez mesafesine gore kayis uzunlugunu hesapla.",
    titleEn: "Pulley Belt Length",
    descriptionEn: "Calculate belt length from pulley diameters and center distance.",
    href: "/tools/belt-length",
    category: "Mechanical",
  },
  {
    id: "torque-power",
    type: "calculator",
    title: "Guc - Tork - Devir",
    description: "kW, hp ve rpm iliskisine gore tork veya guc hesabini yap.",
    titleEn: "Power - Torque - RPM",
    descriptionEn: "Compute torque or power from kW, hp, and rpm.",
    href: "/tools/torque-power",
    category: "Mechanical",
    tags: ["torque"],
    lastUpdated: "2026-01-29",
  },
  {
    id: "strength-statics",
    type: "bundle",
    title: "Mukavemet ve Statik",
    description: "Eksenel, kesme ve burkulma icin hizli mukavemet hesaplari.",
    titleEn: "Strength & Statics",
    descriptionEn: "Quick strength checks for axial, shear, and buckling.",
    href: "/tools/strength-statics",
    category: "Mechanical",
    tags: ["pressure"],
  },
  {
    id: "machine-elements",
    type: "bundle",
    title: "Makine Elemanlari",
    description: "Rulman omru, kamali mil ve disli yukleri icin hesaplar.",
    titleEn: "Machine Elements",
    descriptionEn: "Calculations for bearing life, keyed shafts, and gear loads.",
    href: "/tools/machine-elements",
    category: "Mechanical",
  },
  {
    id: "fluids-hvac",
    type: "bundle",
    title: "Akiskanlar ve HVAC",
    description: "Reynolds, basinc kaybi ve kanal hizi icin hizli hesaplar.",
    titleEn: "Fluids & HVAC",
    descriptionEn: "Quick calculations for Reynolds, pressure loss, and duct velocity.",
    href: "/tools/fluids-hvac",
    category: "General Engineering",
    tags: ["flow", "pressure"],
  },
  {
    id: "heat-energy",
    type: "bundle",
    title: "Isi Transferi ve Enerji",
    description: "LMTD, iletim ve enerji tahminleri icin temel hesaplar.",
    titleEn: "Heat Transfer & Energy",
    descriptionEn: "Basics for LMTD, conduction, and energy estimates.",
    href: "/tools/heat-energy",
    category: "General Engineering",
    tags: ["thermal"],
  },
  {
    id: "materials-manufacturing",
    type: "bundle",
    title: "Malzeme ve Imalat",
    description: "Kesme parametreleri ve toleranslari icin hizli karar yardimi.",
    titleEn: "Materials & Manufacturing",
    descriptionEn: "Quick decisions for cutting parameters and tolerances.",
    href: "/tools/materials-manufacturing",
    category: "General Engineering",
  },
  {
    id: "production-project",
    type: "bundle",
    title: "Uretim ve Proje",
    description: "Takt, OEE ve proje sureleri icin pratik hesaplamalar.",
    titleEn: "Production & Project",
    descriptionEn: "Practical calculations for takt, OEE, and project durations.",
    href: "/tools/production-project",
    category: "General Engineering",
  },
  {
    id: "gear-design",
    type: "guide",
    title: "Disli Tasarimi",
    description: "Disli tasarimi icin genel bakis ve temel hesaplama girisi.",
    titleEn: "Gear Design",
    descriptionEn: "Overview and entry point for gear design calculations.",
    href: "/tools/gear-design",
    category: "Mechanical",
    tags: ["torque"],
  },
  {
    id: "gear-calculators",
    type: "bundle",
    title: "Disli Hesaplayicilar",
    description: "Disli orani, modulu ve temas degerleri icin hesaplayicilar.",
    titleEn: "Gear Calculators",
    descriptionEn: "Calculators for gear ratio, module, and contact values.",
    href: "/tools/gear-design/calculators",
    category: "Mechanical",
  },
  {
    id: "gear-backlash",
    type: "calculator",
    title: "Disli Backlash",
    description: "Backlash degisini ve uygun ayar araligini hesapla.",
    titleEn: "Gear Backlash",
    descriptionEn: "Estimate backlash and recommended adjustment range.",
    href: "/tools/gear-design/calculators/backlash-calculator",
    category: "Mechanical",
  },
  {
    id: "gear-contact-ratio",
    type: "calculator",
    title: "Disli Temas Orani",
    description: "Disli temas oranini ve guvenli temas sinirini hesapla.",
    titleEn: "Gear Contact Ratio",
    descriptionEn: "Calculate contact ratio and safe contact limits.",
    href: "/tools/gear-design/calculators/contact-ratio-calculator",
    category: "Mechanical",
  },
  {
    id: "gear-force-torque",
    type: "calculator",
    title: "Disli Kuvvet ve Tork",
    description: "Disli torku ve tasiyici kuvvetleri hesapla.",
    titleEn: "Gear Force & Torque",
    descriptionEn: "Compute gear torque and transmitted forces.",
    href: "/tools/gear-design/calculators/force-torque-calculator",
    category: "Mechanical",
    tags: ["torque"],
  },
  {
    id: "gear-helix-axial",
    type: "calculator",
    title: "Helis Disli Aksiyel",
    description: "Helis dislilerde aksiyel kuvvet ve helis etkisini hesapla.",
    titleEn: "Helical Gear Axial",
    descriptionEn: "Calculate axial force and helix effect in helical gears.",
    href: "/tools/gear-design/calculators/helix-axial-calculator",
    category: "Mechanical",
  },
  {
    id: "gear-module",
    type: "calculator",
    title: "Disli Modul",
    description: "Disli modulunu ve temel boyutlari hesapla.",
    titleEn: "Gear Module",
    descriptionEn: "Compute gear module and base dimensions.",
    href: "/tools/gear-design/calculators/module-calculator",
    category: "Mechanical",
  },
  {
    id: "gear-ratio",
    type: "calculator",
    title: "Disli Oran",
    description: "Disli oranini ve cikis hizini hesapla.",
    titleEn: "Gear Ratio",
    descriptionEn: "Calculate gear ratio and output speed.",
    href: "/tools/gear-design/calculators/ratio-calculator",
    category: "Mechanical",
  },
  {
    id: "gear-viscosity",
    type: "calculator",
    title: "Disli Yag Viskozitesi",
    description: "Disli yaglama viskozitesi icin hizli secim araci.",
    titleEn: "Gear Oil Viscosity",
    descriptionEn: "Quick selector for gear lubrication viscosity.",
    href: "/tools/gear-design/calculators/viscosity-selector",
    category: "Mechanical",
  },
  {
    id: "gear-weight",
    type: "calculator",
    title: "Disli Agirlik Optimizasyonu",
    description: "Disli agirligini azaltmak icin basit optimizasyon araci.",
    titleEn: "Gear Weight Optimization",
    descriptionEn: "Simple tool to reduce gear weight.",
    href: "/tools/gear-design/calculators/weight-optimization",
    category: "Mechanical",
  },
  {
    id: "gear-simulations",
    type: "bundle",
    title: "Disli Simulasyonlari",
    description: "Disli davranisini test etmek icin simulasyon sayfasi.",
    titleEn: "Gear Simulations",
    descriptionEn: "Simulation pages to test gear behavior.",
    href: "/tools/gear-design/simulations",
    category: "Mechanical",
  },
  {
    id: "sealing-guide",
    type: "guide",
    title: "Sizdirmazlik Rehberi",
    description: "Conta ve sizdirmazlik elemanlari icin pratik referanslar.",
    titleEn: "Sealing Guide",
    descriptionEn: "Practical references for seals and sealing elements.",
    href: "/tools/sealing-guide",
    category: "General Engineering",
  },
  {
    id: "coating-guide",
    type: "guide",
    title: "Kaplama Rehberi",
    description: "Kaplama turleri ve korozyon korumasi icin ozet bilgi.",
    titleEn: "Coating Guide",
    descriptionEn: "Summary of coating types and corrosion protection.",
    href: "/tools/coating-guide",
    category: "General Engineering",
  },
  {
    id: "material-cards",
    type: "guide",
    title: "Malzeme Kartlari",
    description: "Malzeme ozelliklerine hizli ulasim icin kartlar.",
    titleEn: "Material Cards",
    descriptionEn: "Cards for quick access to material properties.",
    href: "/tools/material-cards",
    category: "General Engineering",
  },
  {
    id: "heat-treatment",
    type: "guide",
    title: "Isil Islem",
    description: "Isil islem adimlari ve pratik kalite kontrol notlari.",
    titleEn: "Heat Treatment",
    descriptionEn: "Heat treatment steps and quality control notes.",
    href: "/tools/heat-treatment",
    category: "General Engineering",
  },
];

export const getToolCopy = (tool: ToolCatalogItem, locale: Locale) => {
  if (locale === "en") {
    return {
      title: tool.titleEn ?? tool.title,
      description: tool.descriptionEn ?? tool.description,
    };
  }
  return { title: tool.title, description: tool.description };
};

